### ISSUE TITLE
Corrections costs do not appear after running data foundation

### ISSUE THREAD

**Issue by vinaybenny** [nz-social-investment-unit/social_investment_data_foundation#2]
Initially reported by users from PwC.

**Comment by vinaybenny** [comment]
The root cause is that the variable that stores the list of tables sial_wrapper_rollup macro retains previous values in cases where no sial tables are fetched for a particular agency. The issue is not limited to Corrections. This has been fixed by resetting the variable everytime before use.

**Comment by ernestynne** [comment]
Bug fix is awaiting IDI signout expected within a week.
