### ISSUE TITLE
Sandpit schema is hard coded in many files

### ISSUE THREAD

**Issue by ellisp** [nz-social-investment-unit/social_investment_data_foundation#4]
Around 20 files in ./sasautos/ and other folders of this repo have the SIA's IDI_Sandpit schema (DL-MAA2016-15) hard coded into it and it will need to be changed to the schema available to other projects that obviously can't write to that schema.  In the long term a solution would be to parameterise this, in the short term perhaps just a note in the readme alerting people to the need to do these changes.

**Comment by ernestynne** [comment]
The following files need to be signed out and pushed through to master
$ find . -type f -print0 | xargs -0 grep -l "DL-MAA2016-15"
./si_align_sialevents_to_periods.sas
./si_fetch_sial_datasets_by_agency.sas
./si_get socialhousing_indicator.sas
./si_get_b4sc_scores.sas
./si_get_birth_outcomes.sas
./si_get_contact_record.sas
./si_get_diabetes.sas
./si_get_ece_participation.sas
./si_get_freq_address_changes.sas
./si_get_household_type.sas
./si_get_mha_indicator.sas
./si_get_T1_benefit.sas
./si_get_te_reo.sas
./si_setup.sas
./si_wrapper_sial_rollup.sas

**Comment by ernestynne** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SIDF issue fix - hard coding of our personal schema into several macros](https://trello.com/c/EnXKkDW5/88-sidf-issue-fix-hard-coding-of-our-personal-schema-into-several-macros)

**Comment by ernestynne** [comment]
Most of these are just examples in the headers or test examples. The `./si_wrapper_sial_rollup.sas` has been updated and we are in the process of retesting prior to signing out.

**Comment by vinaybenny** [comment]
This has been fixed with the commit  d1556d8.
